//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRepairService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring
    {
        public int MonitoringID { get; set; }
        public int RequestID { get; set; }
        public Nullable<int> ProcessingTime { get; set; }
        public Nullable<int> QualityRating { get; set; }
        public Nullable<decimal> Costs { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
