//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRepairService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string ResourcesUsed { get; set; }
        public string HelpProvided { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
